FROM {gpu_image_choice}
WORKDIR /code
ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0
RUN apt update
RUN apt install -y gcc
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .